spring.application.name=testFlow

# Server Configuration
server.port=8084

# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/taskFlow_db
spring.datasource.username=postgres
spring.datasource.password=682682
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.web.pageable.default-page-size=20
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=true
spring.jpa.properties.hibernate.query.in_clause_parameter_padding=true