spring.application.name=taskFlow

# Server Configuration
server.port=8084

# Datasource Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/taskflow_db
spring.datasource.username=postgres
spring.datasource.password=682682
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.web.pageable.default-page-size=20
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=true
spring.jpa.properties.hibernate.query.in_clause_parameter_padding=true

# Mail Service Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=htetkyawswarlinn44@gmail.com
spring.mail.password=ekivbxohqiftyyuo
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.servlet.multipart.max-file-size=200MB
spring.servlet.multipart.max-request-size=200MB


spring.app.jwtSecret=mySecretKey123912738dgsdfg4532dfgerety334556dfhe5y44rq3erfgwe4twetq2wef34
spring.app.jwtExpirationMs=3000000
spring.app.jwtCookieName= springBootTaskFlow
